name: preflight
services:
  postgres:
    image: postgres:17-alpine
    container_name: pf-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - pf-data:/var/lib/postgresql/data
      - ./entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pf-net
volumes:
  pf-data:
networks:
  pf-net:
